### ISSUE TITLE
How did you export the model

### ISSUE THREAD

**Issue by CodesInTheShell** [Dharani1008/Autokeras_pneumonia_prediction#1]
Is this the similar command you use to export the model?

first
```
model = clf.export_model()
model.save("model_autokeras_chest_xray.h5")
```
or
second

`clf.export_keras_model("model_autokeras_chest_xray.h5")`

or
third

model = clf.export_model()
model.load_searcher().load_best_model().produce_keras_model().save('model_autokeras_chest_xray.h5')

**Comment by Dharani1008** [comment]
Try this method,
try:
    model.save("model_autokeras_chest_xray1", save_format="tf")
except:
    model.save("model_autokeras_chest_xray1.h5")
